### ISSUE TITLE
when you exit the emulator, there is a whistle

### ISSUE THREAD

**Issue by spielvan** [xjsxjs197/WiiSXRX_2022#8] opened 2022-07-01 16:44 UTC
when it leaves the emulator, it beeps, sounding like radio interference.

**Comment by saulfabregwiivc** [comment] 2022-07-01 19:38
i can't reproduce this.
i don't hear anything when i exit the emulator.

**Comment by spielvan** [comment] 2022-07-01 20:46
Strange, here when I leave it and it stays on the black screen, just before going back to HBC it kind of whistles, but it takes seconds and stops, the interesting thing is that I've heard this same whistle, I just don't remember if it was on wiirx or not64.

**Comment by xjsxjs197** [comment] 2022-07-02 02:33
I have the same problem here, and I haven't paid attention to it. It seems that this problem is not easy to solve.

**Comment by gamecube007** [comment] 2022-07-02 07:19
I have this beep sound in WiiSXRX_2022, too.
You can also hear this sound on the old WiiSXR 2.3.
You can't hear the beep on WiiSXRX from niuus.

**Comment by xjsxjs197** [comment] 2022-09-02 00:59
Delay processing was added when closing the simulator. It seems that this problem does not occur now. Please help confirm again after the official release

**Closed by xjsxjs197** 2022-09-02 00:59 UTC
