### ISSUE TITLE
force ntsc PAL games 

### ISSUE THREAD

**Issue by AlfredoDore** [xjsxjs197/WiiSXRX_2022#225] opened 2024-05-13 18:40 UTC
When forcing NTSC, Resident Evil 1, Dino Crisis 1 and 2, Spyro 1, 2 and 3, Parasite Eve 2 and Metal Guear Solid have a cropped screen, however, in version 3.0 this does not happen
![IMG_20240522_165553091](https://github.com/xjsxjs197/WiiSXRX_2022/assets/90729203/3076e4e4-21f8-4461-8a7f-78a9281526a9)

**Comment by xjsxjs197** [comment] 2024-05-30 03:03
By default, the old software rendering GPU plugin is used. Please try the latest compiled version.

[boot.zip](https://github.com/xjsxjs197/WiiSXRX_2022/files/15493188/boot.zip)

**Comment by saulfabregwiivc** [comment] 2024-06-03 23:52
That issue happened on both old and new GPU plugins, but recently this got fixed on these merged PRs:
https://github.com/xjsxjs197/WiiSXRX_2022/pull/237 (for old GPU), https://github.com/xjsxjs197/WiiSXRX_2022/pull/238 (for new GPU).

Since i personally tested my new changes with forcing to NTSC the PAL games, i can confirm there's no more issues anymore.
I think this issue should be closed now. :)

**Closed** 2024-06-04 02:03 UTC
