### ISSUE TITLE
Posibility of backporting the GPU hack "Slow linked list processing" from PCSX-ReARMed?

### ISSUE THREAD

**Issue by saulfabregwiivc** [xjsxjs197/WiiSXRX_2022#143] opened 2023-10-15 03:44 UTC
Hi there @xjsxjs197 (also pinging @Jokippo if he's interested in it)

Seeing that you're applying and merging the database for fix some games from PCSX-ReARMed, i'd like to ask you if you can backport this commit which adds the GPU hack "Slow linked list processing"?, here:
https://github.com/libretro/pcsx_rearmed/commit/fae38d7aa986b5c0c156808b12e155de8fc0713d

(don't know but i think this also needs adding the plugin GPUlib to WiiStation for this case)

This hack allows some menus and screens of some PS1 games to display correctly.
Explanation:
"Slower but more accurate GPU linked list processing. Needed by only a few games like Vampire Hunter D."

As i said, there are some games affected because this hack isn't implemented here, as shown:

Crash Bash - no text and corrupted info in PAUSE screen
https://github.com/libretro/pcsx_rearmed/issues/478

![crashbash1](https://github.com/xjsxjs197/WiiSXRX_2022/assets/66485640/b080bb3a-95f4-44df-9cbc-95c060af717c)

Bomberman Fantasy Race - invisible RETRY/QUIT menu
https://github.com/libretro/pcsx_rearmed/issues/776

Final Fantasy IV - various graphical glitches when in game
https://github.com/libretro/pcsx_rearmed/issues/132

With that commit mentioned, these games are finally playable on PCSX-ReARMed.

Is it possible to add this hack so those games mentioned can be playable in WiiStation? Thank you so much, appreciate your hard work. :)

**Comment by xjsxjs197** [comment] 2023-10-15 09:08
Okay, let me try it and try to import various hacks from PcsxRearm into WiiStation as much as possible

**Comment by saulfabregwiivc** [comment] 2023-10-27 16:55
@xjsxjs197 sorry for the question but how's the progress in it? I really want to play Crash Bash and Bomberman Fantasy Race without the issues that happen without this hack :)

**Comment by xjsxjs197** [comment] 2023-10-28 11:33
A version has been submitted, but there still seem to be some issues with the 'gpu_busy_hack,' possibly caused by other factors as well. Further confirmation is still needed

**Comment by saulfabregwiivc** [comment] 2023-10-28 18:39
Just tried the new commit in the branch RearmCdromCdiso, and the GPU hack "Slow linked list processing" seems to work well (tested Crash Bash and Bomberman Fantasy Race).

About Hot Wheels Turbo Racing, i'm also having the exact same issue you have (getting returned to the Wii System Menu at the first LOADING screen).

Will test other games.

**Comment by xjsxjs197** [comment] 2023-10-30 00:54
The error in gpu_busy_hack has been fixed, and we have also tested many games. Game [Star Wars – Episode I] cannot be read, and game [F1 one] gets stuck at the initial screen. No issues have been found with the others.

**Comment by saulfabregwiivc** [comment] 2023-10-30 15:49
Thanks for fixing that, HWTR is working now.

If you're talking about the Studio33 F1 games, i think it's related to ICache.
I was about to ask you: are you also going to integrate the latest ICache code from upstream PCSX-ReARMed to WiiStation for both Lightrec and PPC dynarec?
I've noticed that some games (Xenogears, Studio33 F1 games, EA Sports F1 2000, etc.) needs emulation of the ICache (instruction cache).

About SW Episode I - The Phantom Menace, i'll try to see if it's an issue in WiiStation, or also in PCSX-ReARMed.

I will test other games and tell the results, but by now these info should help you for try to fix some issues with some games.

**Comment by saulfabregwiivc** [comment] 2023-10-31 00:49
SW Episode I - The Phantom Menace doesn't even boot in PCSX-ReARMed. I reported it here: https://github.com/libretro/pcsx_rearmed/issues/787
So it's not just a WiiStation/WiiSX issue.

SW Episode I The Jedi Battles plays just fine here.

**Comment by saulfabregwiivc** [comment] 2023-10-31 02:02
I tested the Studio33 F1 games on this new version of WiiStation and these are the results:

**Formula One Arcade (PAL)** - works, but you need to let the entire racers presentation video to be played or else it will result in black screen
**Formula One '99 (NTSC)** - works
**Formula One 2000 (NTSC)** - works
**Formula One 2001 (PAL)** - works

Also tested these EA Sports F1 games:
**EA Sports F1 2000** - crashes at LOADING screen when trying to start a race
**EA Sports F1 Championship Season 2000** - crashes at LOADING screen when trying to start a race

All of these were tested with Lightrec.
The EA Sports F1 games can be played on the PPC dynarec though.

@xjsxjs197 So i was going to ask: what F1 game were you trying to play? I think EA Sports F1 2000?

**Comment by saulfabregwiivc** [comment] 2023-10-31 02:05
After testing, WiiSX can emulate with Lightrec the EA Sports F1 games.
Maybe it's related to ICache code?

Can you try integrating the latest ICache emulation code from PCSX-ReARMed to both Lightrec and PPC dynarec?

**Comment by xjsxjs197** [comment] 2023-10-31 13:21
> @xjsxjs197 So i was going to ask: what F1 game were you trying to play? I think EA Sports F1 2000?
Yes, it is.

> Can you try integrating the latest ICache emulation code from PCSX-ReARMed to both Lightrec and PPC dynarec?
Due to the dynamic compilation, there is no simulation of ICache. This feature only exists in static compilation.
It appears to be an issue from elsewhere. I'll take a look at the other parts of the code to investigate further.

**Comment by xjsxjs197** [comment] 2023-11-08 05:14
The requirements here should have been fulfilled. Close it now.

**Closed by xjsxjs197** 2023-11-08 05:14 UTC

**Comment by saulfabregwiivc** [comment] 2024-03-21 00:06
unrelated to this but the latest commits of moving to MEM2 memory both **SPU 512 kB buffer** (https://github.com/xjsxjs197/WiiSXRX_2022/commit/ee79e9fc87501c075e5abeea676e10bba042329e) and **Lightrec 4 MB code buffer** (https://github.com/xjsxjs197/WiiSXRX_2022/commit/0a0ee9ad0c4ce57383603d03137432fbcb55ebb9) solved the crash of EA Sports F1 2000 in Lightrec, again thanks a lot!
